---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: avarteqgmbh/pipeline-utils

inputs:
  - name: ci-utils
  - name: repository

run:
  path: ci-utils/ci/shared/tasks/create-pr/task.sh

params:
  GITHUB_USER:
  GITHUB_TOKEN:
  PR_HEAD_BRANCH:
  PR_BASE_BRANCH:
