---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: ruby

inputs:
  - name: app
  - name: version

outputs:
  - name: changelog-artifacts

run:
  path: app/ci/tasks/build-changelog/task.rb
