---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang

inputs:
  - name: app
  - name: gin-gonic-gin
    path: deps/gin-gonic-gin

outputs:
  - name: updated-app

run:
  path: app/ci/tasks/update-dependencies/task.sh
